from enum import Enum
class DataType(Enum):
    MOVIE = 1
    COLLECTION = 2
    KEYWORDS = 3.2
    KEYWORDS_VMESNA = 3.1
    LINKS = 4
    RATINGS = 5
    GENRES = 6
    PRODUCTION_COMPANY = 7
    PRODUCTION_COUNTRY = 8
    PEOPLE = 9
    SPOKEN_LANGUAGES = 10
    SPOKEN_LANGUAGES_JEZIKU = 13
    PRODUCIRA = 11
    PRODUCIRA_COUNTRY = 12
    VSTILU = 14
    CREDITS = 15
    CAST = 16
    CREW = 17
